### ISSUE TITLE
500 Error - Cannot read property toLowerCase of undefined

### ISSUE THREAD

**Issue by iriarte300** [un33k/node-ipware#11] opened 2016-04-22 16:28 UTC
I am getting some random errors that I cannot find the reason why. Any idea? Thanks!

`Sending 500 ("Server Error") response:
 TypeError: Cannot read property 'toLowerCase' of undefined
    at Object._me.is_private_ip (/node_modules/ipware/index.js:55:20)
    at Object._me.get_ip (/node_modules/ipware/index.js:147:22)
    at Object.module.exports.parse (/api/services/HitService.js:14:30)
    at Object.bound (/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports.view (/api/controllers/HitController.js:20:34)
    at bound (/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at routeTargetFnWrapper (/node_modules/sails/lib/router/bind.js:179:5)
    at callbacks (/node_modules/sails/node_modules/express/lib/router/index.js:164:37)
    at param (/node_modules/sails/node_modules/express/lib/router/index.js:138:11)
    at param (/node_modules/sails/node_modules/express/lib/router/index.js:135:11)
    at pass (/node_modules/sails/node_modules/express/lib/router/index.js:145:5)
    at nextRoute (/node_modules/sails/node_modules/express/lib/router/index.js:100:7)
    at callbacks (/node_modules/sails/node_modules/express/lib/router/index.js:167:11)
    at /node_modules/sails/lib/router/bind.js:187:7
    at alwaysAllow (/node_modules/sails/lib/hooks/policies/index.js:207:11)
    at routeTargetFnWrapper (/node_modules/sails/lib/router/bind.js:179:5) [TypeError: Cannot read property 'toLowerCase' of undefined]`

**Comment by un33k** [comment] 2016-04-22 16:40
"ip" passes many checks before it hits line 55. "undefined" would have been caught already by that point.  Please reinstall the module to the latest one to rule out file corruption. Also post back anything you find that might help in debugging this.

**Comment by un33k** [comment] 2016-07-11 22:05
Closing due to lack of information and follow up.  No data on deployment, environment and how to reproduce.

**Closed by un33k** 2016-07-11 22:05 UTC
